apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
spec:
  clusterIP: None
  selector:
    project: roboshop
    app: mongodb
    tier: db
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
    