apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
spec:
  clusterIP: None
  selector:
    project: roboshop
    app: mysql
    tier: db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306