apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    app: mysql 
    tier: db
spec:
  serviceName: "mysql"
  replicas: {{ .Values.statefulset.replicas }}
  selector:
    matchLabels:
      project: roboshop
      app: mysql
      tier: db
  spec:
    containers:
    - name: mysql
      image: "rakeshn88/mysql:{{ .Values.statefulset.imageVersion }}"
      envFrom:
      - configMapRef:
          name: mysql
      - secretRef:
          name: mysql
      args:
      - "--ignore-db-dir=lost+found"
      volumeMounts:
      - name: mysql-data
        mountPaths: /var/lib/mysql