apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
spec:
  clusterIP: None
  selector:
    project: roboshop
    app: redis
    tier: db
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
