apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: roboshop
spec:
  type: LoadBalancer
  selector:
    project: roboshop
    app: web
    tier: web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
