apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    app: rabbitmq
    tier: db
spec:
  serviceName: "rabbitmq"
  replicas: {{ .Values.statefulset.replicas }}
  selector:
    matchLabels:
      project: roboshop
      app: rabbitmq
      tier: db
  spec:
    containers:
    - name: rabbitmq
      image: rabbitmq
      imagePullPolicy: Always
      envFrom:
      - secretRef:
          name: rabbitmq
      volumeMounts:
      - name: rabbitmq-data
        mountPath: /var/lib/rabbitmq
        