apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    app: catalogue
    tier: app
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      project: roboshop
      app: catalogue
      tier: app
  template:
    metadata:
      labels:
        project: roboshop
        app: catalogue
        tier: app
    spec:
      containers:
      - name: catalogue
        image: "rakeshn88/catalogue:{{ .Values.deployment.imageVersion }}"
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: catalogue
              