apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
spec:
  type: ClusterIP
  selector:
    project: roboshop
    app: catalogue
    tier: app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080